# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [1]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [21]:
import numpy as np
import pandas as pd
import datetime

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [20]:
data = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data",
    sep = "\s+", engine='python',  header=0, parse_dates = [[0,1,2]], )
data.rename(columns = {"Yr_Mo_Dy":"DATE"}, inplace=True)
data

,DATE,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [23]:
def fix(x):
  year = x.year - 100 if x.year > 1989 else x.year
  return datetime.date(year, x.month, x.day)
data["DATE"]=data["DATE"].apply(fix)

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [24]:
data.set_index("DATE", inplace=True)
data

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
DATE,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [25]:
data.isna().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [26]:
data.count()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [27]:
np.mean(data.mean())

10.227982360836924

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [28]:
loc_stats = data.describe()
loc_stats = loc_stats.transpose()
loc_stats

      count       mean       std   min    25%    50%    75%    max
RPT  6568.0  12.362987  5.618413  0.67   8.12  11.71  15.92  35.80
VAL  6571.0  10.644314  5.267356  0.21   6.67  10.17  14.04  33.37
ROS  6572.0  11.660526  5.008450  1.50   8.00  10.92  14.67  33.84
KIL  6569.0   6.306468  3.605811  0.00   3.58   5.75   8.42  28.46
SHA  6572.0  10.455834  4.936125  0.13   6.75   9.96  13.54  37.54
BIR  6574.0   7.092254  3.968683  0.00   4.00   6.83   9.67  26.16
DUB  6571.0   9.797343  4.977555  0.00   6.00   9.21  12.96  30.37
CLA  6572.0   8.495053  4.499449  0.00   5.09   8.08  11.42  31.08
MUL  6571.0   8.493590  4.166872  0.00   5.37   8.17  11.19  25.88
CLO  6573.0   8.707332  4.503954  0.04   5.33   8.29  11.63  28.21
BEL  6574.0  13.121007  5.835037  0.13   8.71  12.50  16.88  42.38
MAL  6570.0  15.599079  6.699794  0.67  10.71  15.00  19.83  42.54

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [29]:
day_stats = data.agg(["min","mean", "max", "std"], axis=1)
day_stats

             min       mean    max       std
1961-01-01  9.29  13.018182  18.50  2.808875
1961-01-02  6.50  11.336364  17.54  3.188994
1961-01-03  6.17  11.641818  18.50  3.681912
1961-01-04  1.79   6.619167  11.75  3.198126
1961-01-05  6.17  10.630000  13.33  2.445356
...          ...        ...    ...       ...
1978-12-27  8.08  16.708333  40.08  7.868076
1978-12-28  5.00  15.150000  41.46  9.687857
1978-12-29  8.71  14.890000  29.58  5.756836
1978-12-30  9.13  15.367500  28.79  5.540437
1978-12-31  9.59  15.402500  27.29  5.702483

[6574 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [100]:
full = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data",
                  sep = "\s+")
Jan = full.query("Yr == 61 | Yr == 62 & Mo == 1")
Jan.set_index(["Yr", "Mo", "Dy"], inplace=True)
Jan.mean()

RPT    12.496547
VAL    10.573333
ROS    11.459112
KIL     7.004082
SHA    10.952411
BIR     7.807247
DUB    10.087150
CLA     8.917107
MUL     8.728295
CLO     9.966101
BEL    13.727197
MAL    13.837023
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [118]:
full.groupby(full.Yr).mean()

,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr,,,,,,,,,,,,,,
61,6.526027,15.720548,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
62,6.526027,15.720548,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
63,6.526027,15.720548,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
64,6.513661,15.756831,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
65,6.526027,15.720548,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
66,6.526027,15.720548,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
67,6.526027,15.720548,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
68,6.513661,15.756831,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
69,6.526027,15.720548,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
70,6.526027,15.720548,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
71,6.526027,15.720548,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
72,6.513661,15.756831,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
73,6.526027,15.720548,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
74,6.526027,15.720548,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
75,6.526027,15.720548,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
76,6.513661,15.756831,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
77,6.526027,15.720548,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
78,6.526027,15.720548,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [119]:
full.groupby(full.Mo).mean()

,Yr,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Mo,,,,,,,,,,,,,,
1,69.500000,16.000000,14.847325,12.914560,13.299624,7.199498,11.667734,8.054839,11.819355,9.512047,9.543208,10.053566,14.550520,18.028763
2,69.503937,14.614173,13.710906,12.111122,12.879132,6.942411,11.551772,7.633858,11.206024,9.341437,9.313169,9.518051,13.728898,17.156142
3,69.500000,16.000000,13.158687,11.505842,12.648118,7.265907,11.554516,7.959409,11.310179,9.635896,9.700324,10.096953,13.810609,16.909317
4,69.500000,15.500000,12.555648,10.429759,12.204815,6.898037,10.677667,7.441389,10.221315,8.909056,8.930870,9.158019,12.664759,14.937611
5,69.500000,16.000000,11.724032,10.145619,11.550394,6.307487,10.224301,6.942061,8.797738,8.452903,8.040806,8.524857,12.767258,13.736039
6,69.500000,15.500000,10.451317,8.949704,10.361315,5.652278,9.529926,6.410093,8.009556,7.920796,7.639796,7.729185,12.246407,12.861818
7,69.500000,16.000000,9.992007,8.357778,9.349642,5.416935,9.302634,5.972348,7.843501,7.262760,7.544480,7.321416,11.676505,12.800789
8,69.500000,16.000000,10.213411,8.415143,9.993441,5.270681,8.901559,5.891057,7.772312,6.842025,7.240573,7.002783,11.110090,12.565943
9,69.500000,15.500000,11.458519,9.981002,10.756883,5.615176,9.766315,6.566222,8.609722,7.745677,7.610556,7.689278,12.686389,14.761963
10,69.500000,16.000000,12.660610,11.010681,11.453943,6.065215,10.550251,7.159910,9.387778,8.726308,8.347181,8.850376,14.155323,16.697151
11,69.500000,15.500000,13.200722,11.639500,12.293407,6.247611,10.501130,7.134333,10.814861,8.427167,8.604000,8.943167,13.815741,18.114185
12,69.500000,16.000000,14.446398,12.353602,13.212276,6.829910,11.301254,7.963710,11.849050,9.209355,9.447258,9.627670,14.259516,18.697599

### Step 14. Downsample the record to a weekly frequency for each location.

In [139]:
full["Wk"] = ((full.Dy // 7))
full.groupby("Wk").mean()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Wk,,,,,,,,,,,,,,,
0,69.500000,6.500000,3.500000,12.258263,10.514015,11.528843,6.228233,10.193104,6.971134,9.798920,8.341861,8.433151,8.644228,13.003449,15.644811
1,69.500000,6.500000,10.000000,12.572783,10.732202,11.736567,6.365615,10.539782,7.184815,9.835510,8.506058,8.543459,8.648392,13.064788,15.495728
2,69.500000,6.500000,17.000000,12.345344,10.653852,11.741562,6.292589,10.500529,7.117467,9.777295,8.534950,8.432811,8.656759,13.028604,15.582536
3,69.500000,6.500000,24.000000,12.207401,10.620529,11.605423,6.267013,10.467368,7.081892,9.723077,8.504954,8.464739,8.773975,13.157004,15.502057
4,69.502695,6.706199,29.315364,12.472392,10.721781,11.682874,6.431296,10.628787,7.084933,9.909003,8.638571,8.680310,8.904825,13.555836,15.961727

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [145]:
full.groupby(["Mo","Wk"]).describe()

          Yr                                                          Dy  \
       count       mean       std   min    25%   50%    75%   max  count
Mo Wk
1  0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    72.0  69.500000  5.224536  61.0  65.00  69.5  74.00  78.0   72.0
2  0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    22.0  69.590909  5.188440  61.0  65.25  69.5  73.75  78.0   22.0
3  0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    72.0  69.500000  5.224536  61.0  65.00  69.5  74.00  78.0   72.0
4  0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    54.0  69.500000  5.236843  61.0  65.00  69.5  74.00  78.0   54.0
5  0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    72.0  69.500000  5.224536  61.0  65.00  69.5  74.00  78.0   72.0
6  0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    54.0  69.500000  5.236843  61.0  65.00  69.5  74.00  78.0   54.0
7  0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    72.0  69.500000  5.224536  61.0  65.00  69.5  74.00  78.0   72.0
8  0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    72.0  69.500000  5.224536  61.0  65.00  69.5  74.00  78.0   72.0
9  0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    54.0  69.500000  5.236843  61.0  65.00  69.5  74.00  78.0   54.0
10 0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    72.0  69.500000  5.224536  61.0  65.00  69.5  74.00  78.0   72.0
11 0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    54.0  69.500000  5.236843  61.0  65.00  69.5  74.00  78.0   54.0
12 0   108.0  69.500000  5.212315  61.0  65.00  69.5  74.00  78.0  108.0
   1   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   2   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   3   126.0  69.500000  5.208839  61.0  65.00  69.5  74.00  78.0  126.0
   4    72.0  69.500000  5.224536  61.0  65.00  69.5  74.00  78.0   72.0

                  ...      BEL           MAL                             \
            mean  ...      75%    max  count       mean       std   min
Mo Wk             ...
1  0    3.500000  ...  17.5500  36.95  108.0  17.222963  6.969001  4.17
   1   10.000000  ...  19.7300  38.20  126.0  18.277619  6.915453  3.63
   2   17.000000  ...  18.8800  39.04  126.0  18.371984  7.188563  4.63
   3   24.000000  ...  17.7950  32.30  126.0  17.524444  6.954239  3.25
   4   29.500000  ...  20.8675  34.42   72.0  19.083889  7.426756  5.37
2  0    3.500000  ...  18.6225  28.12  108.0  17.031389  6.208971  4.83
   1   10.000000  ...  18.1575  30.63  126.0  17.606587  6.414233  5.09
   2   17.000000  ...  17.4350  32.08  126.0  17.132857  7.142260  3.04
   3   24.000000  ...  18.0075  35.08  126.0  16.756429  6.794499  3.17
   4   28.181818  ...  18.7325  27.29   22.0  17.611364  5.313667  9.54
3  0    3.500000  ...  17.6525  32.63  107.0  15.792991  6.833988  2.46
   1   10.000000  ...  16.8675  29.29  126.0  16.798413  6.117810  4.54
   2   17.000000  ...  19.6475  34.92  125.0  17.567280  8.017048  4.67
   3   24.000000  ...  17.6775  32.21  126.0  17.405079  6.408027  2.04
   4   29.500000  ...  17.8550  28.42   72.0  16.752500  6.527616  3.08
4  0    3.500000  ...  17.4100  25.50  108.0  17.020185  6.546322  4.63
   1   10.000000  ...  16.4900  27.00  126.0  15.694206  6.674786  3.71
   2   17.000000  ...  15.6575  25.84  126.0  14.752698  6.176576  4.17
   3   24.000000  ...  15.3975  25.29  126.0  13.065714  5.721042  2.29
   4   29.000000  ...  16.6500  26.12   54.0  13.806296  5.858206  2.21
5  0    3.500000  ...  16.3125  28.33  108.0  14.251574  6.372238  3.25
   1   10.000000  ...  17.2875  32.91  126.0  14.963571  5.732614  3.88
   2   17.000000  ...  15.5400  23.42  126.0  13.368651  5.745426  3.33
   3   24.000000  ...  15.9375  28.12  126.0  13.809444  5.411334  4.08
   4   29.500000  ...  13.4300  26.38   72.0  11.329028  5.051314  1.75
6  0    3.500000  ...  15.4425  22.34  108.0  12.826019  5.014917  2.58
   1   10.000000  ...  12.9900  23.29  126.0  11.232857  5.351461  2.21
   2   17.000000  ...  16.0000  29.79  126.0  13.426905  5.356230  2.79
   3   24.000000  ...  15.0900  24.58  126.0  13.788413  5.611130  3.58
   4   29.000000  ...  16.8675  24.71   53.0  13.261132  4.722416  4.54
7  0    3.500000  ...  14.6525  24.50  108.0  13.229722  5.371047  4.88
   1   10.000000  ...  14.6575  23.83  126.0  13.088730  5.438758  2.13
   2   17.000000  ...  14.2700  24.41  126.0  12.818810  5.092020  2.29
   3   24.000000  ...  14.6775  24.17  126.0  12.477063  5.521111  2.88
   4   29.500000  ...  15.0075  21.67   72.0  12.188472  4.736321  3.75
8  0    3.500000  ...  13.7325  22.00  108.0  12.485370  4.835078  2.25
   1   10.000000  ...  13.0200  24.08  126.0  11.804365  5.575331  3.04
   2   17.000000  ...  14.9600  24.83  125.0  12.426240  5.699430  2.17
   3   24.000000  ...  15.6775  23.63  126.0  12.844444  5.827810  3.37
   4   29.500000  ...  14.5125  24.71   72.0  13.774722  5.009384  5.50
9  0    3.500000  ...  14.5500  26.46  108.0  13.842037  6.197541  3.37
   1   10.000000  ...  16.2300  25.75  126.0  14.798889  5.795397  3.54
   2   17.000000  ...  14.7800  25.33  126.0  13.760159  6.067915  0.67
   3   24.000000  ...  18.0375  28.79  126.0  15.155476  6.364581  2.08
   4   29.000000  ...  21.0125  26.83   54.0  17.935000  7.211068  3.88
10 0    3.500000  ...  18.2425  34.83  108.0  15.927315  7.127122  2.04
   1   10.000000  ...  16.6475  34.54  126.0  15.119683  5.943251  3.33
   2   17.000000  ...  19.4225  31.88  126.0  17.137619  7.032606  4.08
   3   24.000000  ...  19.3375  38.96  126.0  17.639365  6.107385  6.17
   4   29.500000  ...  18.9800  29.42   72.0  18.192778  5.988472  8.71
11 0    3.500000  ...  18.9200  35.30  108.0  18.317407  7.118500  2.96
   1   10.000000  ...  18.8800  33.34  126.0  18.398254  7.659966  3.00
   2   17.000000  ...  17.5800  31.96  126.0  18.328730  8.555361  2.00
   3   24.000000  ...  17.2575  30.00  126.0  17.631746  6.793048  4.25
   4   29.000000  ...  18.7500  28.79   54.0  17.670000  6.780896  7.08
12 0    3.500000  ...  18.5700  42.38  108.0  19.792130  6.483413  5.09
   1   10.000000  ...  18.6650  29.08  126.0  18.165556  6.350600  6.67
   2   17.000000  ...  18.2800  29.25  126.0  17.889206  6.784905  3.92
   3   24.000000  ...  17.1275  31.25  126.0  17.927063  6.550614  2.62
   4   29.500000  ...  18.2550  30.46   72.0  20.750000  6.462466  7.21


           25%     50%      75%    max
Mo Wk
1  0   12.2650  16.835  22.8850  34.13
   1   12.9500  17.750  23.1800  34.70
   2   13.2800  17.960  22.8675  40.12
   3   12.3525  17.455  22.4550  34.54
   4   13.8450  18.830  23.0575  38.79
2  0   12.9075  16.625  21.4325  33.63
   1   12.3900  17.165  21.6800  35.75
   2   11.4925  16.250  21.9775  38.20
   3   11.5200  16.060  21.3300  34.05
   4   13.2200  17.270  22.1225  29.79
3  0   10.8550  15.670  20.5600  30.63
   1   13.2800  16.375  20.6875  37.59
   2   11.6700  16.330  22.3400  40.37
   3   13.1400  17.580  22.1600  34.00
   4   13.1600  16.420  20.3200  34.08
4  0   11.9500  16.315  20.7100  32.96
   1   11.1200  14.775  20.9100  33.04
   2   10.5500  13.960  17.7500  33.95
   3    8.4300  12.355  16.4200  32.05
   4    8.8925  13.770  18.2700  26.92
5  0   10.1175  13.060  18.3800  28.75
   1   10.8900  14.605  19.2375  28.01
   2    8.8925  13.000  16.7100  32.17
   3   10.0000  13.480  17.4000  29.50
   4    7.5300  11.205  14.2750  28.04
6  0    9.4175  12.250  16.0500  32.79
   1    6.5500  10.835  14.6700  27.16
   2    9.4400  13.355  16.8150  28.38
   3    9.6400  13.060  16.8200  28.08
   4   10.6700  13.170  16.2500  25.17
7  0    8.6675  13.105  16.6725  29.63
   1    9.1025  12.520  16.3200  28.46
   2    9.1700  12.975  16.3575  25.37
   3    8.1900  12.270  15.8600  25.37
   4    9.0975  12.645  15.8975  21.75
8  0    9.3100  12.690  16.2625  24.83
   1    7.1525  10.895  15.0775  29.95
   2    8.2900  11.540  16.0000  34.33
   3    8.3425  12.500  17.1675  26.87
   4   10.2800  12.730  17.3500  27.33
9  0    9.1475  13.520  17.6250  30.34
   1   10.4750  15.060  18.1100  35.13
   2   10.1025  13.730  17.4100  33.09
   3   10.5925  14.750  19.0200  33.42
   4   12.5825  17.725  22.8425  33.63
10 0   11.1475  15.630  20.8000  36.51
   1   10.7200  14.435  19.3100  34.46
   2   11.5725  16.645  22.5600  35.92
   3   12.9800  16.835  21.5900  36.63
   4   13.1175  18.560  21.9950  33.12
11 0   13.2975  18.670  22.0425  37.59
   1   12.4700  17.395  24.2575  38.04
   2   11.5500  17.475  23.7775  41.25
   3   12.9300  17.330  21.3075  35.92
   4   12.7600  16.770  21.5575  32.05
12 0   16.0300  19.125  23.8000  42.54
   1   13.7425  17.975  22.6900  37.12
   2   13.6850  17.790  21.8175  38.25
   3   13.0400  17.580  21.7175  40.08
   4   16.5500  19.170  24.8725  41.46

[60 rows x 112 columns]